In [1]:
import numpy as np

In [2]:
my_matrix = np.array([[1,2,-1,2],
                   [2,4,-2,4],
                   [-1,-2,1,-2]])
print("Matrix")
for row in my_matrix:
    print(row)

Matrix
[ 1  2 -1  2]
[ 2  4 -2  4]
[-1 -2  1 -2]


In [3]:
rank = np.linalg.matrix_rank(my_matrix)
print("Rank of the given Matrix is : ",rank)

Rank of the given Matrix is :  1
